//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMicRemote.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMicRemote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   音声認識で使用するChromeウィンドウのサイズと位置を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChromeSizePoint_Description {
            get {
                return ResourceManager.GetString("ChromeSizePoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声認識ウィンドウのサイズと位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChromeSizePoint_DisplayName {
            get {
                return ResourceManager.GetString("ChromeSizePoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   キー1 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey1_Description {
            get {
                return ResourceManager.GetString("InputKey1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー1 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey1_DisplayName {
            get {
                return ResourceManager.GetString("InputKey1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー2 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey2_Description {
            get {
                return ResourceManager.GetString("InputKey2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー2 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey2_DisplayName {
            get {
                return ResourceManager.GetString("InputKey2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー3 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey3_Description {
            get {
                return ResourceManager.GetString("InputKey3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー3 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey3_DisplayName {
            get {
                return ResourceManager.GetString("InputKey3_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー4 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey4_Description {
            get {
                return ResourceManager.GetString("InputKey4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー4 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey4_DisplayName {
            get {
                return ResourceManager.GetString("InputKey4_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー5 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey5_Description {
            get {
                return ResourceManager.GetString("InputKey5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー5 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey5_DisplayName {
            get {
                return ResourceManager.GetString("InputKey5_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー6 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey6_Description {
            get {
                return ResourceManager.GetString("InputKey6_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー6 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey6_DisplayName {
            get {
                return ResourceManager.GetString("InputKey6_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー7 に紐づける押下するキーを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey7_Description {
            get {
                return ResourceManager.GetString("InputKey7_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー7 の押下キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputKey7_DisplayName {
            get {
                return ResourceManager.GetString("InputKey7_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定情報（Settings.settings）の[{0}]プロパティにおいて、デフォルト値[{1}]の設定値が不正です。該当するEnumの値が取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingErrorMessageInvalidPropertyValue {
            get {
                return ResourceManager.GetString("SettingErrorMessageInvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定情報（Settings.settings）に[{0}]に該当するプロパティは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingErrorMessageNoTargetProperty {
            get {
                return ResourceManager.GetString("SettingErrorMessageNoTargetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定情報（Settings.settings）の[{0}]プロパティにデフォルト値属性（DefaultSettingValueAttribute）が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingErrorMessagePropertyNotHaveDefaultAttribute {
            get {
                return ResourceManager.GetString("SettingErrorMessagePropertyNotHaveDefaultAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [設定エラー] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SimpleFormMatchLabelTextError {
            get {
                return ResourceManager.GetString("SimpleFormMatchLabelTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [設定無] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SimpleFormMatchLabelTextNotSet {
            get {
                return ResourceManager.GetString("SimpleFormMatchLabelTextNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション開始時の音声認識した文字をそのまま入力する機能のモードを指定する。
        ///指定するモードは下記のとおり。
        ///・Off：音声認識した文字をそのまま入力する機能を[OFF]状態とする。
        ///・On：音声認識した文字をそのまま入力する機能を[ON]状態とする。
        ///・OnEnter：音声認識した文字をそのまま入力する機能を入力後Enterを入力するモードで[ON]状態とする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartInputMode_Description {
            get {
                return ResourceManager.GetString("StartInputMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始時の入力モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartInputMode_DisplayName {
            get {
                return ResourceManager.GetString("StartInputMode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション開始時のモードを指定する。
        ///指定するモードは下記のとおり。
        ///・Setting：設定を行うモード、設定画面を表示し、音声認識を停止状態で起動する。
        ///・StartupNormal：アプリケーション開始と共に音声認識を開始するモード、設定画面も表示する。
        ///・StartupMinimize：アプリケーション開始と共に音声認識を開始するモード、設定画面は最小化状態とする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartStartupMode_Description {
            get {
                return ResourceManager.GetString("StartStartupMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始時の起動モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartStartupMode_DisplayName {
            get {
                return ResourceManager.GetString("StartStartupMode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動1 に紐づける起動する対象となるアプリ／ファイルのパスを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath1_Description {
            get {
                return ResourceManager.GetString("StartTargetPath1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動1 のアプリ／ファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath1_DisplayName {
            get {
                return ResourceManager.GetString("StartTargetPath1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動2 に紐づける起動する対象となるアプリ／ファイルのパスを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath2_Description {
            get {
                return ResourceManager.GetString("StartTargetPath2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動2 のアプリ／ファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath2_DisplayName {
            get {
                return ResourceManager.GetString("StartTargetPath2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動3 に紐づける起動する対象となるアプリ／ファイルのパスを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath3_Description {
            get {
                return ResourceManager.GetString("StartTargetPath3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動3 のアプリ／ファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath3_DisplayName {
            get {
                return ResourceManager.GetString("StartTargetPath3_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動4 に紐づける起動する対象となるアプリ／ファイルのパスを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath4_Description {
            get {
                return ResourceManager.GetString("StartTargetPath4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動4 のアプリ／ファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath4_DisplayName {
            get {
                return ResourceManager.GetString("StartTargetPath4_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動5 に紐づける起動する対象となるアプリ／ファイルのパスを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath5_Description {
            get {
                return ResourceManager.GetString("StartTargetPath5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動5 のアプリ／ファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath5_DisplayName {
            get {
                return ResourceManager.GetString("StartTargetPath5_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動6 に紐づける起動する対象となるアプリ／ファイルのパスを指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath6_Description {
            get {
                return ResourceManager.GetString("StartTargetPath6_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動6 のアプリ／ファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTargetPath6_DisplayName {
            get {
                return ResourceManager.GetString("StartTargetPath6_DisplayName", resourceCulture);
            }
        }
    }
}
