//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMicRemote.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// 音声認識に使用する既定の「音声認識用.html」ファイルのパス
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("音声認識に使用する既定の「音声認識用.html」ファイルのパス")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Html\\音声認識用.html")]
        public string ChromeSpeechRecognitionHtmlFilePath {
            get {
                return ((string)(this["ChromeSpeechRecognitionHtmlFilePath"]));
            }
        }
        
        /// <summary>
        /// 「音声認識用.html」において、音声認識認識した文字列をPOSTする際に使用するURLの正規表現（「音声認識用.html」と整合性をとる必要があるパラメータ）
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("「音声認識用.html」において、音声認識認識した文字列をPOSTする際に使用するURLの正規表現（「音声認識用.html」と整合性をとる必要があるパラメータ）")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".RunProcess")]
        public string ChromeSpeechRecognitionPostRegex {
            get {
                return ((string)(this["ChromeSpeechRecognitionPostRegex"]));
            }
        }
        
        /// <summary>
        /// 「音声認識用.html」において、音声認識認識した文字列をPOSTする際に使用するPOSTデータのパラメータ名（「音声認識用.html」と整合性をとる必要があるパラメータ）
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("「音声認識用.html」において、音声認識認識した文字列をPOSTする際に使用するPOSTデータのパラメータ名（「音声認識用.html」と整合性をとる必要があるパ" +
            "ラメータ）")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("txt")]
        public string ChromeSpeechRecognitionPostParamName {
            get {
                return ((string)(this["ChromeSpeechRecognitionPostParamName"]));
            }
        }
        
        /// <summary>
        /// 音声認識用において使用するポート番号
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("音声認識用において使用するポート番号")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49152")]
        public string ChromeSpeechRecognitionPort {
            get {
                return ((string)(this["ChromeSpeechRecognitionPort"]));
            }
            set {
                this["ChromeSpeechRecognitionPort"] = value;
            }
        }
        
        /// <summary>
        /// クライアントのサイズ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("クライアントのサイズ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460, 336")]
        public global::System.Drawing.Size ClientSize {
            get {
                return ((global::System.Drawing.Size)(this["ClientSize"]));
            }
            set {
                this["ClientSize"] = value;
            }
        }
        
        /// <summary>
        /// クライアントの位置
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("クライアントの位置")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point ClientPoint {
            get {
                return ((global::System.Drawing.Point)(this["ClientPoint"]));
            }
            set {
                this["ClientPoint"] = value;
            }
        }
        
        /// <summary>
        /// アプリケーション起動の際の起動モード
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリケーション起動の際の起動モード")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Setting")]
        public string StartStartupMode {
            get {
                return ((string)(this["StartStartupMode"]));
            }
            set {
                this["StartStartupMode"] = value;
            }
        }
        
        /// <summary>
        /// アプリケーション起動の際の入力モード
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリケーション起動の際の入力モード")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Off")]
        public string StartInputMode {
            get {
                return ((string)(this["StartInputMode"]));
            }
            set {
                this["StartInputMode"] = value;
            }
        }
        
        /// <summary>
        /// 音声認識で使用するChromeウィンドウのサイズ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("音声認識で使用するChromeウィンドウのサイズ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 250, 200, 200")]
        public string ChromeSizePoint {
            get {
                return ((string)(this["ChromeSizePoint"]));
            }
            set {
                this["ChromeSizePoint"] = value;
            }
        }
        
        /// <summary>
        /// 入力モードON：Enter無 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("入力モードON：Enter無 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力モード")]
        public string MatchMessageInputModeOn {
            get {
                return ((string)(this["MatchMessageInputModeOn"]));
            }
            set {
                this["MatchMessageInputModeOn"] = value;
            }
        }
        
        /// <summary>
        /// 入力モードON：Enter無 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("入力モードON：Enter無 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力モードエンター")]
        public string MatchMessageInputModeOnEnter {
            get {
                return ((string)(this["MatchMessageInputModeOnEnter"]));
            }
            set {
                this["MatchMessageInputModeOnEnter"] = value;
            }
        }
        
        /// <summary>
        /// 入力モードOFF のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("入力モードOFF のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("モード解除")]
        public string MatchMessageInputModeOff {
            get {
                return ((string)(this["MatchMessageInputModeOff"]));
            }
            set {
                this["MatchMessageInputModeOff"] = value;
            }
        }
        
        /// <summary>
        /// アクティブウィンドウを閉じる のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アクティブウィンドウを閉じる のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("これを閉じて")]
        public string MatchMessageActiveWindowClose {
            get {
                return ((string)(this["MatchMessageActiveWindowClose"]));
            }
            set {
                this["MatchMessageActiveWindowClose"] = value;
            }
        }
        
        /// <summary>
        /// キー入力1 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力1 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("エンター")]
        public string MatchMessageKeyInput1 {
            get {
                return ((string)(this["MatchMessageKeyInput1"]));
            }
            set {
                this["MatchMessageKeyInput1"] = value;
            }
        }
        
        /// <summary>
        /// キー入力2 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力2 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("スペース")]
        public string MatchMessageKeyInput2 {
            get {
                return ((string)(this["MatchMessageKeyInput2"]));
            }
            set {
                this["MatchMessageKeyInput2"] = value;
            }
        }
        
        /// <summary>
        /// キー入力3 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力3 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageKeyInput3 {
            get {
                return ((string)(this["MatchMessageKeyInput3"]));
            }
            set {
                this["MatchMessageKeyInput3"] = value;
            }
        }
        
        /// <summary>
        /// キー入力4 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力4 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageKeyInput4 {
            get {
                return ((string)(this["MatchMessageKeyInput4"]));
            }
            set {
                this["MatchMessageKeyInput4"] = value;
            }
        }
        
        /// <summary>
        /// キー入力5 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力5 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageKeyInput5 {
            get {
                return ((string)(this["MatchMessageKeyInput5"]));
            }
            set {
                this["MatchMessageKeyInput5"] = value;
            }
        }
        
        /// <summary>
        /// キー入力6 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力6 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageKeyInput6 {
            get {
                return ((string)(this["MatchMessageKeyInput6"]));
            }
            set {
                this["MatchMessageKeyInput6"] = value;
            }
        }
        
        /// <summary>
        /// キー入力7 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力7 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageKeyInput7 {
            get {
                return ((string)(this["MatchMessageKeyInput7"]));
            }
            set {
                this["MatchMessageKeyInput7"] = value;
            }
        }
        
        /// <summary>
        /// 押しっぱなし解除のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("押しっぱなし解除のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("キー解除")]
        public string MatchMessageReleaseKey {
            get {
                return ((string)(this["MatchMessageReleaseKey"]));
            }
            set {
                this["MatchMessageReleaseKey"] = value;
            }
        }
        
        /// <summary>
        /// アプリ起動1 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリ起動1 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メモ帳起動")]
        public string MatchMessageExeStart1 {
            get {
                return ((string)(this["MatchMessageExeStart1"]));
            }
            set {
                this["MatchMessageExeStart1"] = value;
            }
        }
        
        /// <summary>
        /// アプリ起動2 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリ起動2 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageExeStart2 {
            get {
                return ((string)(this["MatchMessageExeStart2"]));
            }
            set {
                this["MatchMessageExeStart2"] = value;
            }
        }
        
        /// <summary>
        /// アプリ起動3 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリ起動3 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageExeStart3 {
            get {
                return ((string)(this["MatchMessageExeStart3"]));
            }
            set {
                this["MatchMessageExeStart3"] = value;
            }
        }
        
        /// <summary>
        /// アプリ起動4 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリ起動4 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageExeStart4 {
            get {
                return ((string)(this["MatchMessageExeStart4"]));
            }
            set {
                this["MatchMessageExeStart4"] = value;
            }
        }
        
        /// <summary>
        /// アプリ起動5 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリ起動5 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageExeStart5 {
            get {
                return ((string)(this["MatchMessageExeStart5"]));
            }
            set {
                this["MatchMessageExeStart5"] = value;
            }
        }
        
        /// <summary>
        /// アプリ起動6 のマッチングメッセージ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("アプリ起動6 のマッチングメッセージ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatchMessageExeStart6 {
            get {
                return ((string)(this["MatchMessageExeStart6"]));
            }
            set {
                this["MatchMessageExeStart6"] = value;
            }
        }
        
        /// <summary>
        /// キー入力1の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力1の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x0D:Enter")]
        public string InputKey1 {
            get {
                return ((string)(this["InputKey1"]));
            }
            set {
                this["InputKey1"] = value;
            }
        }
        
        /// <summary>
        /// キー入力2の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力2の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x20:Space")]
        public string InputKey2 {
            get {
                return ((string)(this["InputKey2"]));
            }
            set {
                this["InputKey2"] = value;
            }
        }
        
        /// <summary>
        /// キー入力3の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力3の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00:- なし -")]
        public string InputKey3 {
            get {
                return ((string)(this["InputKey3"]));
            }
            set {
                this["InputKey3"] = value;
            }
        }
        
        /// <summary>
        /// キー入力4の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力4の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00:- なし -")]
        public string InputKey4 {
            get {
                return ((string)(this["InputKey4"]));
            }
            set {
                this["InputKey4"] = value;
            }
        }
        
        /// <summary>
        /// キー入力5の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力5の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00:- なし -")]
        public string InputKey5 {
            get {
                return ((string)(this["InputKey5"]));
            }
            set {
                this["InputKey5"] = value;
            }
        }
        
        /// <summary>
        /// キー入力6の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力6の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00:- なし -")]
        public string InputKey6 {
            get {
                return ((string)(this["InputKey6"]));
            }
            set {
                this["InputKey6"] = value;
            }
        }
        
        /// <summary>
        /// キー入力7の入力キーの設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("キー入力7の入力キーの設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00:- なし -")]
        public string InputKey7 {
            get {
                return ((string)(this["InputKey7"]));
            }
            set {
                this["InputKey7"] = value;
            }
        }
        
        /// <summary>
        /// 起動する対象のパス1の設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("起動する対象のパス1の設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WINDOWS\\system32\\notepad.exe")]
        public string StartTargetPath1 {
            get {
                return ((string)(this["StartTargetPath1"]));
            }
            set {
                this["StartTargetPath1"] = value;
            }
        }
        
        /// <summary>
        /// 起動する対象のパス2の設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("起動する対象のパス2の設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartTargetPath2 {
            get {
                return ((string)(this["StartTargetPath2"]));
            }
            set {
                this["StartTargetPath2"] = value;
            }
        }
        
        /// <summary>
        /// 起動する対象のパス3の設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("起動する対象のパス3の設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartTargetPath3 {
            get {
                return ((string)(this["StartTargetPath3"]));
            }
            set {
                this["StartTargetPath3"] = value;
            }
        }
        
        /// <summary>
        /// 起動する対象のパス4の設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("起動する対象のパス4の設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartTargetPath4 {
            get {
                return ((string)(this["StartTargetPath4"]));
            }
            set {
                this["StartTargetPath4"] = value;
            }
        }
        
        /// <summary>
        /// 起動する対象のパス5の設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("起動する対象のパス5の設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartTargetPath5 {
            get {
                return ((string)(this["StartTargetPath5"]));
            }
            set {
                this["StartTargetPath5"] = value;
            }
        }
        
        /// <summary>
        /// 起動する対象のパス6の設定
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MisaCommon.Configurations.CustomUserConfig.UserSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("起動する対象のパス6の設定")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartTargetPath6 {
            get {
                return ((string)(this["StartTargetPath6"]));
            }
            set {
                this["StartTargetPath6"] = value;
            }
        }
    }
}
