//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources.Type {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HardwareInputPropertyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HardwareInputPropertyMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.Type.HardwareInputPropertyMessage", typeof(HardwareInputPropertyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   メッセージに対するlParamパラメータ（上位）を設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HighlParam_Description {
            get {
                return ResourceManager.GetString("HighlParam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High lParam  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HighlParam_DisplayName {
            get {
                return ResourceManager.GetString("HighlParam_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージに対するlParamパラメータ（下位）を設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LowlParam_Description {
            get {
                return ResourceManager.GetString("LowlParam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low lParam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LowlParam_DisplayName {
            get {
                return ResourceManager.GetString("LowlParam_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力するメッセージを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Description {
            get {
                return ResourceManager.GetString("Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_DisplayName {
            get {
                return ResourceManager.GetString("Message_DisplayName", resourceCulture);
            }
        }
    }
}
