//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources.Type {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputKeyPropertyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputKeyPropertyMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.Type.InputKeyPropertyMessage", typeof(InputKeyPropertyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Altキーを押しているかどうかを指定する
        ///押している場合：True、押していない場合：False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alt_Description {
            get {
                return ResourceManager.GetString("Alt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alt_DisplayName {
            get {
                return ResourceManager.GetString("Alt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrlキーを押しているかどうかを指定する
        ///押している場合：True、押していない場合：False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ctrl_Description {
            get {
                return ResourceManager.GetString("Ctrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ctrl_DisplayName {
            get {
                return ResourceManager.GetString("Ctrl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーコードを指定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyCode_Description {
            get {
                return ResourceManager.GetString("KeyCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyCode_DisplayName {
            get {
                return ResourceManager.GetString("KeyCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shiftキーを押しているかどうかを指定する
        ///押している場合：True、押していない場合：False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shift_Description {
            get {
                return ResourceManager.GetString("Shift_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shift_DisplayName {
            get {
                return ResourceManager.GetString("Shift_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winキーを押しているかどうかを指定する
        ///押している場合：True、押していない場合：False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Win_Description {
            get {
                return ResourceManager.GetString("Win_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Win_DisplayName {
            get {
                return ResourceManager.GetString("Win_DisplayName", resourceCulture);
            }
        }
    }
}
