//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources.Type {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SizePointPropertyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SizePointPropertyMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.Type.SizePointPropertyMessage", typeof(SizePointPropertyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   対象の表示位置のX座標を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositionX_Description {
            get {
                return ResourceManager.GetString("PositionX_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置X座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositionX_DisplayName {
            get {
                return ResourceManager.GetString("PositionX_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の表示位置のY座標を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositionY_Description {
            get {
                return ResourceManager.GetString("PositionY_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置Y座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositionY_DisplayName {
            get {
                return ResourceManager.GetString("PositionY_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のサイズの高さを指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeHeight_Description {
            get {
                return ResourceManager.GetString("SizeHeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeHeight_DisplayName {
            get {
                return ResourceManager.GetString("SizeHeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のサイズの幅を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeWidth_Description {
            get {
                return ResourceManager.GetString("SizeWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeWidth_DisplayName {
            get {
                return ResourceManager.GetString("SizeWidth_DisplayName", resourceCulture);
            }
        }
    }
}
