//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources.Type {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StartProcessInfoPropertyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartProcessInfoPropertyMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.Type.StartProcessInfoPropertyMessage", typeof(StartProcessInfoPropertyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   起動するexeファイルのパスを指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessPath_Description {
            get {
                return ResourceManager.GetString("ProcessPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動するexeファイルのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessPath_DisplayName {
            get {
                return ResourceManager.GetString("ProcessPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動したプロセスのウィンドウのサイズと位置を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizePoint_Description {
            get {
                return ResourceManager.GetString("SizePoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動したプロセスのウィンドウのサイズと位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizePoint_DisplayName {
            get {
                return ResourceManager.GetString("SizePoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動パラメータを指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartupParam_Description {
            get {
                return ResourceManager.GetString("StartupParam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動パラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartupParam_DisplayName {
            get {
                return ResourceManager.GetString("StartupParam_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセス起動後、処理を待つ間隔をミリ秒単位で指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitDelay_Description {
            get {
                return ResourceManager.GetString("WaitDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセス起動後、処理を待つ間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaitDelay_DisplayName {
            get {
                return ResourceManager.GetString("WaitDelay_DisplayName", resourceCulture);
            }
        }
    }
}
