//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources.UserControl {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlListBoxMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlListBoxMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.UserControl.ControlListBoxMessage", typeof(ControlListBoxMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtMinusConfirmDeletionMessage {
            get {
                return ResourceManager.GetString("BtMinusConfirmDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除対象を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtMinusNoChekedMessage {
            get {
                return ResourceManager.GetString("BtMinusNoChekedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動対象を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtUpDownNoChekedMessage {
            get {
                return ResourceManager.GetString("BtUpDownNoChekedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除ボタン（[ー]ボタン）押下時の削除確認メッセージを表示するかのフラグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsShowDeleteConfirmMessageDescription {
            get {
                return ResourceManager.GetString("IsShowDeleteConfirmMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除ボタン（[ー]ボタン）押下時において削除対象有無チェックでNGとなった場合にメッセージを表示するかのフラグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsShowDeleteNoChekedMessageDescription {
            get {
                return ResourceManager.GetString("IsShowDeleteNoChekedMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動ボタン（[↑]、[↓]ボタン）押下時において移動対象有無チェックでNGとなった場合にメッセージを表示するかのフラグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsShowMoveNoChekedMessageDescription {
            get {
                return ResourceManager.GetString("IsShowMoveNoChekedMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロール追加ボタン（[＋]ボタン）押下時に発生する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlusClickDescription {
            get {
                return ResourceManager.GetString("PlusClickDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された行に対する背景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectRowBackColorDescription {
            get {
                return ResourceManager.GetString("SelectRowBackColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///        に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TableRadioButtonText {
            get {
                return ResourceManager.GetString("TableRadioButtonText", resourceCulture);
            }
        }
    }
}
