//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources.UserControl {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyInputSettingMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyInputSettingMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.UserControl.KeyInputSettingMessage", typeof(KeyInputSettingMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   コントロールが、その内容に合わせて自動的に高さを変更するかどうかを指定する。
        ///AutoSizeプロパティがFalseの場合のみ指定が可能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoSizeHeightDescription {
            get {
                return ResourceManager.GetString("AutoSizeHeightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動高さ調整時におけるコンボボックス領域の表示行数を指定する。
        ///0を指定した場合は全てを表示するサイズに調整する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoSizeHeightDisplayLinesDescription {
            get {
                return ResourceManager.GetString("AutoSizeHeightDisplayLinesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールが、その内容に合わせて自動的に幅を変更するかどうかを指定する。
        ///AutoSizeプロパティがFalseの場合のみ指定が可能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoSizeWidthDescription {
            get {
                return ResourceManager.GetString("AutoSizeWidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMEキーのコンボボックスの有効・無効を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledImeKeyDescription {
            get {
                return ResourceManager.GetString("EnabledImeKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力キーのコンボボックスの有効・無効を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledInputKeyDescription {
            get {
                return ResourceManager.GetString("EnabledInputKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マウスのコンボボックスの有効・無効を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledMouseDescription {
            get {
                return ResourceManager.GetString("EnabledMouseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作キーのコンボボックスの有効・無効を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledOperateKeyDescription {
            get {
                return ResourceManager.GetString("EnabledOperateKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特殊キーのコンボボックスの有効・無効を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledSpecialKeyDescription {
            get {
                return ResourceManager.GetString("EnabledSpecialKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutCategory {
            get {
                return ResourceManager.GetString("LayoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyChangeCategory {
            get {
                return ResourceManager.GetString("PropertyChangeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定データを変更した時に発生する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingDataChangedDescription {
            get {
                return ResourceManager.GetString("SettingDataChangedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー入力：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SummaryTextFormat {
            get {
                return ResourceManager.GetString("SummaryTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   押しっぱなし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SummaryTextKeepPressing {
            get {
                return ResourceManager.GetString("SummaryTextKeepPressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMEキーのコンボボックスの表示・非表示を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisibleImeKeyDescription {
            get {
                return ResourceManager.GetString("VisibleImeKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力キーのコンボボックスの表示・非表示を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisibleInputKeyDescription {
            get {
                return ResourceManager.GetString("VisibleInputKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マウスのコンボボックスの表示・非表示を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisibleMouseDescription {
            get {
                return ResourceManager.GetString("VisibleMouseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作キーのコンボボックスの表示・非表示を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisibleOperateKeyDescription {
            get {
                return ResourceManager.GetString("VisibleOperateKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特殊キーのコンボボックスの表示・非表示を指定する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisibleSpecialKeyDescription {
            get {
                return ResourceManager.GetString("VisibleSpecialKeyDescription", resourceCulture);
            }
        }
    }
}
