//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisaCommon.MessageResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyName() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MisaCommon.MessageResources.KeyName", typeof(KeyName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   - なし - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x00_None {
            get {
                return ResourceManager.GetString("Key0x00_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x0000FFFF_KeyCode {
            get {
                return ResourceManager.GetString("Key0x0000FFFF_KeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift修飾子 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x00010000_Shift {
            get {
                return ResourceManager.GetString("Key0x00010000_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl修飾子 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x00020000_Control {
            get {
                return ResourceManager.GetString("Key0x00020000_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt修飾子 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x00040000_Alt {
            get {
                return ResourceManager.GetString("Key0x00040000_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x000F0000_Modifiers {
            get {
                return ResourceManager.GetString("Key0x000F0000_Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x01_LButton {
            get {
                return ResourceManager.GetString("Key0x01_LButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x02_RButton {
            get {
                return ResourceManager.GetString("Key0x02_RButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Break に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x03_Cancel {
            get {
                return ResourceManager.GetString("Key0x03_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中央クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x04_MButton {
            get {
                return ResourceManager.GetString("Key0x04_MButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第１拡張ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x05_XButton1 {
            get {
                return ResourceManager.GetString("Key0x05_XButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第２拡張ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x06_XButton2 {
            get {
                return ResourceManager.GetString("Key0x06_XButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BackSpace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x08_Back {
            get {
                return ResourceManager.GetString("Key0x08_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x09_Tab {
            get {
                return ResourceManager.GetString("Key0x09_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LF：ラインフィード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x0A_LineFeed {
            get {
                return ResourceManager.GetString("Key0x0A_LineFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x0C_Clear {
            get {
                return ResourceManager.GetString("Key0x0C_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x0D_Enter {
            get {
                return ResourceManager.GetString("Key0x0D_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x10_ShiftKey {
            get {
                return ResourceManager.GetString("Key0x10_ShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x11_ControlKey {
            get {
                return ResourceManager.GetString("Key0x11_ControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x12_Menu {
            get {
                return ResourceManager.GetString("Key0x12_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x13_Pause {
            get {
                return ResourceManager.GetString("Key0x13_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CapsLock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x14_CapsLock {
            get {
                return ResourceManager.GetString("Key0x14_CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   かな/ローマ字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x15_KanaMode {
            get {
                return ResourceManager.GetString("Key0x15_KanaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IME Junjaモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x17_JunjaMode {
            get {
                return ResourceManager.GetString("Key0x17_JunjaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IME Finalモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x18_FinalMode {
            get {
                return ResourceManager.GetString("Key0x18_FinalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英数/漢字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x19_KanjiMode {
            get {
                return ResourceManager.GetString("Key0x19_KanjiMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Esc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x1B_Escape {
            get {
                return ResourceManager.GetString("Key0x1B_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x1C_IMEConvert {
            get {
                return ResourceManager.GetString("Key0x1C_IMEConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x1D_IMENonconvert {
            get {
                return ResourceManager.GetString("Key0x1D_IMENonconvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IME Accept に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x1E_IMEAccept {
            get {
                return ResourceManager.GetString("Key0x1E_IMEAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IME モード変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x1F_IMEModeChange {
            get {
                return ResourceManager.GetString("Key0x1F_IMEModeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x20_Space {
            get {
                return ResourceManager.GetString("Key0x20_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PageUp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x21_PageUp {
            get {
                return ResourceManager.GetString("Key0x21_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PageDown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x22_PageDown {
            get {
                return ResourceManager.GetString("Key0x22_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x23_End {
            get {
                return ResourceManager.GetString("Key0x23_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x24_Home {
            get {
                return ResourceManager.GetString("Key0x24_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ← に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x25_Left {
            get {
                return ResourceManager.GetString("Key0x25_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x26_Up {
            get {
                return ResourceManager.GetString("Key0x26_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   → に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x27_Right {
            get {
                return ResourceManager.GetString("Key0x27_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↓ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x28_Down {
            get {
                return ResourceManager.GetString("Key0x28_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x29_Select {
            get {
                return ResourceManager.GetString("Key0x29_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x2A_Print {
            get {
                return ResourceManager.GetString("Key0x2A_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x2B_Execute {
            get {
                return ResourceManager.GetString("Key0x2B_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrintScreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x2C_PrintScreen {
            get {
                return ResourceManager.GetString("Key0x2C_PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x2D_Insert {
            get {
                return ResourceManager.GetString("Key0x2D_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x2E_Delete {
            get {
                return ResourceManager.GetString("Key0x2E_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x2F_Help {
            get {
                return ResourceManager.GetString("Key0x2F_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x30_D0 {
            get {
                return ResourceManager.GetString("Key0x30_D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x31_D1 {
            get {
                return ResourceManager.GetString("Key0x31_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x32_D2 {
            get {
                return ResourceManager.GetString("Key0x32_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x33_D3 {
            get {
                return ResourceManager.GetString("Key0x33_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x34_D4 {
            get {
                return ResourceManager.GetString("Key0x34_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x35_D5 {
            get {
                return ResourceManager.GetString("Key0x35_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x36_D6 {
            get {
                return ResourceManager.GetString("Key0x36_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x37_D7 {
            get {
                return ResourceManager.GetString("Key0x37_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x38_D8 {
            get {
                return ResourceManager.GetString("Key0x38_D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x39_D9 {
            get {
                return ResourceManager.GetString("Key0x39_D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x41_A {
            get {
                return ResourceManager.GetString("Key0x41_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x42_B {
            get {
                return ResourceManager.GetString("Key0x42_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x43_C {
            get {
                return ResourceManager.GetString("Key0x43_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x44_D {
            get {
                return ResourceManager.GetString("Key0x44_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x45_E {
            get {
                return ResourceManager.GetString("Key0x45_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x46_F {
            get {
                return ResourceManager.GetString("Key0x46_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x47_G {
            get {
                return ResourceManager.GetString("Key0x47_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x48_H {
            get {
                return ResourceManager.GetString("Key0x48_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x49_I {
            get {
                return ResourceManager.GetString("Key0x49_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   J に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x4A_J {
            get {
                return ResourceManager.GetString("Key0x4A_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x4B_K {
            get {
                return ResourceManager.GetString("Key0x4B_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   L に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x4C_L {
            get {
                return ResourceManager.GetString("Key0x4C_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x4D_M {
            get {
                return ResourceManager.GetString("Key0x4D_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   N に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x4E_N {
            get {
                return ResourceManager.GetString("Key0x4E_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   O に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x4F_O {
            get {
                return ResourceManager.GetString("Key0x4F_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   P に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x50_P {
            get {
                return ResourceManager.GetString("Key0x50_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x51_Q {
            get {
                return ResourceManager.GetString("Key0x51_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x52_R {
            get {
                return ResourceManager.GetString("Key0x52_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x53_S {
            get {
                return ResourceManager.GetString("Key0x53_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x54_T {
            get {
                return ResourceManager.GetString("Key0x54_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x55_U {
            get {
                return ResourceManager.GetString("Key0x55_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   V に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x56_V {
            get {
                return ResourceManager.GetString("Key0x56_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x57_W {
            get {
                return ResourceManager.GetString("Key0x57_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x58_X {
            get {
                return ResourceManager.GetString("Key0x58_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x59_Y {
            get {
                return ResourceManager.GetString("Key0x59_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x5A_Z {
            get {
                return ResourceManager.GetString("Key0x5A_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x5B_LWin {
            get {
                return ResourceManager.GetString("Key0x5B_LWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x5C_RWin {
            get {
                return ResourceManager.GetString("Key0x5C_RWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x5D_Apps {
            get {
                return ResourceManager.GetString("Key0x5D_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x5F_Sleep {
            get {
                return ResourceManager.GetString("Key0x5F_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x60_NumPad0 {
            get {
                return ResourceManager.GetString("Key0x60_NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x61_NumPad1 {
            get {
                return ResourceManager.GetString("Key0x61_NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x62_NumPad2 {
            get {
                return ResourceManager.GetString("Key0x62_NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x63_NumPad3 {
            get {
                return ResourceManager.GetString("Key0x63_NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x64_NumPad4 {
            get {
                return ResourceManager.GetString("Key0x64_NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x65_NumPad5 {
            get {
                return ResourceManager.GetString("Key0x65_NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x66_NumPad6 {
            get {
                return ResourceManager.GetString("Key0x66_NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x67_NumPad7 {
            get {
                return ResourceManager.GetString("Key0x67_NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x68_NumPad8 {
            get {
                return ResourceManager.GetString("Key0x68_NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   9(テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x69_NumPad9 {
            get {
                return ResourceManager.GetString("Key0x69_NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ * ](テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x6A_Multiply {
            get {
                return ResourceManager.GetString("Key0x6A_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ + ](テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x6B_Add {
            get {
                return ResourceManager.GetString("Key0x6B_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区切り記号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x6C_Separator {
            get {
                return ResourceManager.GetString("Key0x6C_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ - ](テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x6D_Subtract {
            get {
                return ResourceManager.GetString("Key0x6D_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ . ](テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x6E_Decimal {
            get {
                return ResourceManager.GetString("Key0x6E_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ / ](テンキー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x6F_Divide {
            get {
                return ResourceManager.GetString("Key0x6F_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x70_F1 {
            get {
                return ResourceManager.GetString("Key0x70_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x71_F2 {
            get {
                return ResourceManager.GetString("Key0x71_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x72_F3 {
            get {
                return ResourceManager.GetString("Key0x72_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x73_F4 {
            get {
                return ResourceManager.GetString("Key0x73_F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x74_F5 {
            get {
                return ResourceManager.GetString("Key0x74_F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F6 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x75_F6 {
            get {
                return ResourceManager.GetString("Key0x75_F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F7 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x76_F7 {
            get {
                return ResourceManager.GetString("Key0x76_F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x77_F8 {
            get {
                return ResourceManager.GetString("Key0x77_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x78_F9 {
            get {
                return ResourceManager.GetString("Key0x78_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F10 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x79_F10 {
            get {
                return ResourceManager.GetString("Key0x79_F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F11 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x7A_F11 {
            get {
                return ResourceManager.GetString("Key0x7A_F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F12 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x7B_F12 {
            get {
                return ResourceManager.GetString("Key0x7B_F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F13 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x7C_F13 {
            get {
                return ResourceManager.GetString("Key0x7C_F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F14 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x7D_F14 {
            get {
                return ResourceManager.GetString("Key0x7D_F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F15 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x7E_F15 {
            get {
                return ResourceManager.GetString("Key0x7E_F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F16 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x7F_F16 {
            get {
                return ResourceManager.GetString("Key0x7F_F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F17 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x80_F17 {
            get {
                return ResourceManager.GetString("Key0x80_F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F18 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x81_F18 {
            get {
                return ResourceManager.GetString("Key0x81_F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F19 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x82_F19 {
            get {
                return ResourceManager.GetString("Key0x82_F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F20 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x83_F20 {
            get {
                return ResourceManager.GetString("Key0x83_F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F21 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x84_F21 {
            get {
                return ResourceManager.GetString("Key0x84_F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F22 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x85_F22 {
            get {
                return ResourceManager.GetString("Key0x85_F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F23 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x86_F23 {
            get {
                return ResourceManager.GetString("Key0x86_F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F24 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x87_F24 {
            get {
                return ResourceManager.GetString("Key0x87_F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NumLock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x90_NumLock {
            get {
                return ResourceManager.GetString("Key0x90_NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScrollLock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0x91_Scroll {
            get {
                return ResourceManager.GetString("Key0x91_Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA0_LShiftKey {
            get {
                return ResourceManager.GetString("Key0xA0_LShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA1_RShiftKey {
            get {
                return ResourceManager.GetString("Key0xA1_RShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA2_LControlKey {
            get {
                return ResourceManager.GetString("Key0xA2_LControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA3_RControlKey {
            get {
                return ResourceManager.GetString("Key0xA3_RControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA4_LMenu {
            get {
                return ResourceManager.GetString("Key0xA4_LMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA5_RMenu {
            get {
                return ResourceManager.GetString("Key0xA5_RMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA6_BrowserBack {
            get {
                return ResourceManager.GetString("Key0xA6_BrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_進む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA7_BrowserForward {
            get {
                return ResourceManager.GetString("Key0xA7_BrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA8_BrowserRefresh {
            get {
                return ResourceManager.GetString("Key0xA8_BrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_中止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xA9_BrowserStop {
            get {
                return ResourceManager.GetString("Key0xA9_BrowserStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xAA_BrowserSearch {
            get {
                return ResourceManager.GetString("Key0xAA_BrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_お気に入り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xAB_BrowserFavorites {
            get {
                return ResourceManager.GetString("Key0xAB_BrowserFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザ_ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xAC_BrowserHome {
            get {
                return ResourceManager.GetString("Key0xAC_BrowserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量[ミュート] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xAD_VolumeMute {
            get {
                return ResourceManager.GetString("Key0xAD_VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量[ - ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xAE_VolumeDown {
            get {
                return ResourceManager.GetString("Key0xAE_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量[ + ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xAF_VolumeUp {
            get {
                return ResourceManager.GetString("Key0xAF_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディア_次のトラック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB0_MediaNextTrack {
            get {
                return ResourceManager.GetString("Key0xB0_MediaNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディア_前のトラック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB1_MediaPreviousTrack {
            get {
                return ResourceManager.GetString("Key0xB1_MediaPreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディア_停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB2_MediaStop {
            get {
                return ResourceManager.GetString("Key0xB2_MediaStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディア_再生/一時停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB3_MediaPlayPause {
            get {
                return ResourceManager.GetString("Key0xB3_MediaPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB4_LaunchMail {
            get {
                return ResourceManager.GetString("Key0xB4_LaunchMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディア選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB5_SelectMedia {
            get {
                return ResourceManager.GetString("Key0xB5_SelectMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットキー１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB6_LaunchApplication1 {
            get {
                return ResourceManager.GetString("Key0xB6_LaunchApplication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットキー２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xB7_LaunchApplication2 {
            get {
                return ResourceManager.GetString("Key0xB7_LaunchApplication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ :* ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xBA_OemSemicolon {
            get {
                return ResourceManager.GetString("Key0xBA_OemSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ ;+ ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xBB_Oemplus {
            get {
                return ResourceManager.GetString("Key0xBB_Oemplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ ,&lt; ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xBC_Oemcomma {
            get {
                return ResourceManager.GetString("Key0xBC_Oemcomma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ -= ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xBD_OemMinus {
            get {
                return ResourceManager.GetString("Key0xBD_OemMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ .&gt; ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xBE_OemPeriod {
            get {
                return ResourceManager.GetString("Key0xBE_OemPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ /? ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xBF_OemQuestion {
            get {
                return ResourceManager.GetString("Key0xBF_OemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ @` ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xC0_Oemtilde {
            get {
                return ResourceManager.GetString("Key0xC0_Oemtilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ [{ ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xDB_OemOpenBrackets {
            get {
                return ResourceManager.GetString("Key0xDB_OemOpenBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ \| ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xDC_OemPipe {
            get {
                return ResourceManager.GetString("Key0xDC_OemPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ ]} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xDD_OemCloseBrackets {
            get {
                return ResourceManager.GetString("Key0xDD_OemCloseBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ ^~ ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xDE_OemQuotes {
            get {
                return ResourceManager.GetString("Key0xDE_OemQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xDF_Oem8 {
            get {
                return ResourceManager.GetString("Key0xDF_Oem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ \_ ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xE2_OemBackslash {
            get {
                return ResourceManager.GetString("Key0xE2_OemBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessKey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xE5_ProcessKey {
            get {
                return ResourceManager.GetString("Key0xE5_ProcessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xE7_Packet {
            get {
                return ResourceManager.GetString("Key0xE7_Packet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英数 CapsLock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF0_VK_OEM_ATTN {
            get {
                return ResourceManager.GetString("Key0xF0_VK_OEM_ATTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタカナ ひらがな に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF2_VK_OEM_COPY {
            get {
                return ResourceManager.GetString("Key0xF2_VK_OEM_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角／全角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF3_VK_OEM_AUTO {
            get {
                return ResourceManager.GetString("Key0xF3_VK_OEM_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローマ字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF5_VK_OEM_BACKTAB {
            get {
                return ResourceManager.GetString("Key0xF5_VK_OEM_BACKTAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF6_Attn {
            get {
                return ResourceManager.GetString("Key0xF6_Attn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crsel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF7_Crsel {
            get {
                return ResourceManager.GetString("Key0xF7_Crsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exsel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF8_Exsel {
            get {
                return ResourceManager.GetString("Key0xF8_Exsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erase Eof に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xF9_EraseEof {
            get {
                return ResourceManager.GetString("Key0xF9_EraseEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xFA_Play {
            get {
                return ResourceManager.GetString("Key0xFA_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xFB_Zoom {
            get {
                return ResourceManager.GetString("Key0xFB_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xFC_NoName {
            get {
                return ResourceManager.GetString("Key0xFC_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PA1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xFD_Pa1 {
            get {
                return ResourceManager.GetString("Key0xFD_Pa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OemClear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Key0xFE_OemClear {
            get {
                return ResourceManager.GetString("Key0xFE_OemClear", resourceCulture);
            }
        }
    }
}
